### ISSUE TITLE
Phone Number

### ISSUE THREAD

**Issue by Layalekiameh** [Ashwinbicholiya/scanpay#5]
the phone number not working any suggestion

**Comment by Ashwinbicholiya** [comment]
You have to enter 10 digit phone number.

**Comment by Layalekiameh** [comment]
Thank you can we extend it to be more than 10 digit number. Thank you
Good work keep going

**Comment by Ashwinbicholiya** [comment]
Yes we can extend it to any digits we want.

**Comment by Layalekiameh** [comment]
Can you explain how can i did that because i am new sorry for disturbing you😍😍

**Comment by Ashwinbicholiya** [comment]
Just simply changes in the code of phone number Text field. There i added the form validator , in that i check if length of number is <10  then it will throws an error.

**Comment by Ashwinbicholiya** [comment]
![IMG_20201011_143534](https://user-images.githubusercontent.com/47949413/95674658-3d544200-0bcf-11eb-864e-2a0fa0365feb.jpg)

**Comment by Layalekiameh** [comment]
Thank you very much

**Comment by Layalekiameh** [comment]
One more question i try to add a product but not visible in the store thank you

**Comment by Ashwinbicholiya** [comment]
You cant add products caz i changes some rules in firestore database.

**Comment by Ashwinbicholiya** [comment]
Only i can add products.

**Comment by Ashwinbicholiya** [comment]
Yes but you can create a new database.

**Comment by Layalekiameh** [comment]
Any suggestions how can i do it to add my own product

**Comment by Ashwinbicholiya** [comment]
Are you add the barcode of the products along with name and price and imageurl.

**Comment by Ashwinbicholiya** [comment]
Then i can change rules in database and allows you to add some pruducts.

**Comment by Layalekiameh** [comment]
Any tutorials how can create a new database firestore with all features (scan. Add product. Login. Signup...) thank you for your help you arr amazing

**Comment by Ashwinbicholiya** [comment]
Are you new in flutter?

**Comment by Layalekiameh** [comment]
Yes this is my first project in flutter

**Comment by Ashwinbicholiya** [comment]
Oh you can connect me on insta or linked there i can share some tutorial to you.

**Comment by Layalekiameh** [comment]
Instagram good
